allowBuilds:
  '@clerk/shared': false
  '@parcel/watcher': true
  '@swc/core': true
  esbuild: true
  msgpackr-extract: false
  sharp: true
  unrs-resolver: false
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
