import { ImageResponse } from "next/og";

export const contentType = "image/png";

/**
 * Dynamic favicon for Danaël — generates PNG icons from the brand mark.
 *
 * Renders the lime-green "D" mark on a navy gradient background, matching
 * the Logo SVG. Multiple sizes (32 / 192 / 512) are generated by Next.js via
 * the `generateImageMetadata` route handler — accessible at /icon?id=<id>.
 */
export default function Icon({
  id = "32",
}: {
  id?: string;
}) {
  const sizeNum = id === "512" ? 512 : id === "192" ? 192 : 32;
  const markSize = Math.round(sizeNum * 0.7);
  const fontSize = Math.round(sizeNum * 0.45);

  return new ImageResponse(
    (
      <div
        style={{
          width: "100%",
          height: "100%",
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          background: "linear-gradient(135deg, #0a1b43 0%, #060e1e 100%)",
          fontSize: 0,
        }}
      >
        <div
          style={{
            width: markSize,
            height: markSize,
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            background: "#93d91a",
            borderRadius: sizeNum * 0.18,
            color: "#0a1b43",
            fontSize,
            fontWeight: 800,
            fontFamily: "sans-serif",
            letterSpacing: -0.04,
          }}
        >
          D
        </div>
      </div>
    ),
    {
      width: sizeNum,
      height: sizeNum,
    },
  );
}

export function generateImageMetadata() {
  return [
    { id: "32", size: { width: 32, height: 32 }, contentType, alt: "Danaël favicon" },
    { id: "192", size: { width: 192, height: 192 }, contentType, alt: "Danaël icon" },
    { id: "512", size: { width: 512, height: 512 }, contentType, alt: "Danaël large icon" },
  ];
}
